### PR TITLE
Fix the authomatic view error handler

### PR DESCRIPTION
**Pull request by ale-rt**
Fix the authomatic view when it is reporting an exception that does not have a `message` attribute.

This happens, e.g. when you have a `ValueError`.

```
>>> ValueError().message
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ValueError' object has no attribute 'message'
```

### CODE REVIEW

**Comment by ale-rt** [comment]
The tests look broken after https://github.com/collective/pas.plugins.authomatic/pull/74 CC @jensens @avoinea

**Comment by ale-rt** [comment]
About the tests, I see that already changing the layer goes a long way:
```
--- a/src/pas/plugins/authomatic/testing.py
+++ b/src/pas/plugins/authomatic/testing.py
@@ -12,6 +12,7 @@ from plone.testing.zope import WSGI_SERVER_FIXTURE
 from Products.CMFCore.interfaces import ISiteRoot
 from Products.PlonePAS.setuphandlers import migrate_root_uf
 from zope.component import provideUtility
+from plone.app.testing import PLONE_FIXTURE
 
 import pas.plugins.authomatic
 
@@ -21,7 +22,7 @@ ORIGINAL_CSRF_DISABLED = auto.CSRF_DISABLED
 
 class PasPluginsAuthomaticZopeLayer(Layer):
 
-    defaultBases = (INTEGRATION_TESTING,)
+    defaultBases = (PLONE_FIXTURE,)
```

Anyway, then it breaks while trying to get `self["app"]`. I hope I will have time to do more checks later.

**Comment by ale-rt** [comment]
> About the tests, I see that already changing the layer goes a long way:
> 
> ```
> --- a/src/pas/plugins/authomatic/testing.py
> +++ b/src/pas/plugins/authomatic/testing.py
> @@ -12,6 +12,7 @@ from plone.testing.zope import WSGI_SERVER_FIXTURE
>  from Products.CMFCore.interfaces import ISiteRoot
>  from Products.PlonePAS.setuphandlers import migrate_root_uf
>  from zope.component import provideUtility
> +from plone.app.testing import PLONE_FIXTURE
>  
>  import pas.plugins.authomatic
>  
> @@ -21,7 +22,7 @@ ORIGINAL_CSRF_DISABLED = auto.CSRF_DISABLED
>  
>  class PasPluginsAuthomaticZopeLayer(Layer):
>  
> -    defaultBases = (INTEGRATION_TESTING,)
> +    defaultBases = (PLONE_FIXTURE,)
> ```
> 
> Anyway, then it breaks while trying to get `self["app"]`. I hope I will have time to do more checks later.

I noticed that we already have a proper layer, see https://github.com/collective/pas.plugins.authomatic/pull/77
